'use client';

import React, { useState } from 'react';
import Shell from '@/components/layout/Shell';
import {
  FileSpreadsheet,
  Download,
  Calendar,
  CheckCircle2,
  Lock,
  Sparkles,
} from 'lucide-react';
import { INITIAL_REPORTS } from '@/lib/data/mockData';
import { SystemReport } from '@/types/admin';
import { useAuth } from '@/context/AuthContext';

export default function ReportsPage() {
  const { hasPermission } = useAuth();
  const [reports, setReports] = useState<SystemReport[]>(INITIAL_REPORTS);
  const [toastMsg, setToastMsg] = useState('');

  const canExport = hasPermission('analytics.export') || hasPermission('finance.export');

  const handleDownload = (rep: SystemReport) => {
    if (!canExport) {
      setToastMsg('Permission Denied: *.export authorization required.');
      return;
    }
    setToastMsg(`Generating & downloading ${rep.title} (${rep.format}). Action logged to audit trail.`);
  };

  return (
    <Shell>
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-6 rounded-3xl glass-card border border-sky-500/20">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full bg-sky-500/20 text-sky-400 border border-sky-500/30 text-[10px] font-mono font-bold">
              SYSTEM REPORTING & EXPORT ENGINE
            </span>
          </div>
          <h1 className="text-2xl font-black text-white">Reports & PDF / CSV Exports</h1>
          <p className="text-xs text-slate-400">
            Generate permission-controlled financial summaries, adherence logs, AI telemetry reports, and user growth matrices.
          </p>
        </div>
      </div>

      {toastMsg && (
        <div className="p-3.5 rounded-2xl bg-sky-500/10 border border-sky-500/30 text-sky-400 text-xs flex items-center justify-between animate-in fade-in">
          <span>{toastMsg}</span>
          <button onClick={() => setToastMsg('')} className="text-slate-400 hover:text-white">✕</button>
        </div>
      )}

      {/* Report Types Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {reports.map((rep) => (
          <div key={rep.id} className="p-6 rounded-3xl glass-card border border-slate-800 space-y-4 flex flex-col justify-between">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="px-2.5 py-0.5 rounded bg-sky-500/20 text-sky-400 border border-sky-500/30 text-[10px] font-mono uppercase">
                  {rep.format} Report
                </span>
                <span className="text-[10px] text-slate-500 font-mono">{(rep.sizeBytes / 1000000).toFixed(2)} MB</span>
              </div>
              <h3 className="text-base font-bold text-white leading-tight">{rep.title}</h3>
              <span className="text-[11px] text-slate-400 block">Generated by: {rep.generatedBy}</span>
            </div>

            <button
              onClick={() => handleDownload(rep)}
              disabled={!canExport}
              className={`w-full py-2.5 px-4 rounded-xl text-xs font-semibold flex items-center justify-center gap-2 transition-all ${
                canExport
                  ? 'bg-slate-900 border border-slate-800 hover:border-sky-500/40 text-sky-400 hover:text-white'
                  : 'bg-slate-950 text-slate-600 border border-slate-900 cursor-not-allowed'
              }`}
            >
              {!canExport ? <Lock className="w-3.5 h-3.5" /> : <Download className="w-4 h-4" />} Download {rep.format} File
            </button>
          </div>
        ))}
      </div>
    </Shell>
  );
}
